config/routes.rb
Rails.application.routes.draw do
  root to: 'static#index'
  
  get '/feed',   to: 'static#feed'
  get '/api' => redirect('/swagger/dist/index.html?url=/api-docs.json')
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/movies/:id/follow', to: 'movies#follow'
  get '/movies/:id/unfollow', to: 'movies#unfollow'
  
  resources :users
  resources :movies do
    resources :topics, only: [:new, :create, :edit, :update, :show, :destroy] do
      resources :posts, only: [:new, :create, :edit, :update, :show, :destroy]
    end
  end
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user
  belongs_to :movie
  has_many :posts
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  skip_before_action	:verify_authenticity_token
  before_action :require_token, only: [:create]
  swagger_controller	:topics,	'Topics'


  # GET /topics/1
  # GET /topics/1.json
  swagger_api :show do
    summary 'Returns one topic'
    param :path, :movie_id, :integer, :required, "Movie id"
    param :path, :id, :integer, :required, "Topic id"
    notes 'Notes...'
end
  def show
  end

  # GET /topics/new
  def new
	@movie = Movie.find(params[:movie_id])
	@topic = @movie.topics.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  swagger_api :create do
    summary "Create new topic"
    param :header, "Authorization", :string, :required, "Authentication token"
    param :path, :movie_id, :integer, :required, "Movie id"
    param :form, "topic[title]", :string, :required, "Title of a topic"
end
  def create
    @movie = Movie.find(params[:movie_id])
	@topic = @movie.topics.new(topic_params)
    @topic.user = current_user

    respond_to do |format|
      if @topic.save
        format.html { redirect_to [@movie, @topic], notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  swagger_api :update do
    summary "Update a topic"
    param :path, :id, :integer, :required, "Topic id"
    param :path, :movie_id, :integer, :required, "Movie id"
    param :form, "topic[title]", :string, :required, "Topic title"
end
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to [@movie, @topic], notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  swagger_api :destroy do
    summary 'Destroys a topic'
    param :path, :id, :integer, :required, "Topic id"
    param :path, :movie_id, :integer, :required, "Movie id"
    notes 'Notes...'
end
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @movie = Movie.find(params[:movie_id])
	  @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:title, :user, :movie_id)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for [@movie, @topic] do |form| %>
  <% if topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :topic_title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Topics</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>User</th>
      <th>Movie</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.title %></td>
        <td><%= topic.user %></td>
        <td><%= topic.movie %></td>
        <td><%= link_to 'Show', topic %></td>
        <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
        <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topic', new_topic_path %>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Back', @movie %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @topic.title %> by <%= link_to @topic.user.name, @topic.user %></h1>
<h2><%= link_to @movie.name, @movie %></h2>

<hr>
<h1>Lista odpowiedzi</h1>
<% if @topic.posts.length == 0 %>
	Nie ma żadnych odpowiedzi
<% else %>
	<ul>
	<% @topic.posts.each do |post| %>
		<li>
			<strong><%= post.user.name %> pisze:</strong> <%= post.body %>
		</li>
	<% end %>
	</ul>
<% end %>

<hr>
<% if logged_in? && current_user.follows?(@movie) %>
<%= link_to "Dodaj odpowiedź", new_movie_topic_post_path(@movie,@topic) %>
<% end %>
<hr>

<%= link_to 'Edit', edit_movie_topic_path(@movie, @topic) %> |
<%= link_to 'Back', @movie %>